---

  ospf_process_id: Underlay
  ospf_area: 0
  ospf_global_key: XXXX

  asn: 65535

  bgp_neighbors:
  - { remote_as: 65535, neighbor: 10.137.255.1, update_source: Loopback0 }
  - { remote_as: 65535, neighbor: 10.137.255.2, update_source: Loopback0 }

  rp_address: 10.137.255.254

  l2_trunk_interfaces:
  - { interface: Ethernet1/1, trunk_vlans: 10 }

  l2_access_interfaces:
  - { interface: Ethernet1/3, access_vlan: 248 }

  vlans_l2vni:
  - { vlan_id: 11, vni_id: 10011, addr: 10.0.11.1, mask: 24, mcast_grp: 239.0.0.11, vrf: Tenant-1 }

  vlans_l3vni:
  - { vlan_id: 248, vni_id: 5248, vrf: MSP_248 }

  vrfs:
  - { vrf: MSP_248, vni_id: 5248, afi: ipv4, safi: unicast }
